media/index.md
=> Add Nature paper link to Media page

speaking/index.md
=> [SPEAKING] Add PyData Cambridge info to Speaking page

CONTRIBUTING.md
This PR adds contributing guidelines to the repo
- Created `CONTRIBUTING.md`
=> :sparkles: Add Contributing Guidelines

README.md
Updates the docs to be more descriptive.
- Gives overview of repo structure
- Adds link to CoC and contributing guidelines
- Gives attribution for jekyll theme
=> :pencil: Update README.md

speaking/index.md
This PR adds a link to my CogX slides to the speaking page
- `speaking/index.md`
=> ✨ Add CogX link to speaking list

.github/workflows/check_spelling.yml
This PR adds a GitHub Action that will perform a spellcheck on all Markdown files.
- Added `.github/workflows/check_spelling.yml`
=> 👷 Add spell check CI workflow

.github/ISSUE_TEMPLATE/blog-post-template.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md
This Pull Request updates the comments in the issue and PR templates.
- Issue and PR template files
=> Update comments in issue/PR templates

.github/workflows/ci.yml
This Pull Request is attempting to fix broken CI by removing an environment variable
- Env variable removed from `ci.yml`
=> Remove env variable

speaking/index.md
=> ✨ Add JuliaCon and EuroPython to Speaking page

media/index.md
Updating the media page with a couple of links.
- Added link to TPS panel from CogX 2020 on YouTube
- Added link to Reproducible Data Science episode of Turing Podcast on Spotify
=> 🍱 Update media links

.github/workflows/ci.yml
Updates `gh-pages` trigger to `main`
=> 👷 Switch CI triggers

.github/workflows/ci.yml
Update build-and-deploy CI job to checkout submodules and use a slightly different build approach
=> 👷 Update build-and-deploy CI job

README.md
This PR adds some helpful commands to the README and updates the site theme using the git submodule
- Updated README
- Updated theme in themes/anatole
=> Update docs and site theme

content/blog/collabw21.md
This PR adds a blog reflecting on CollabW21
=> Add CollabW21 blog

content/speaking.md
=> 🗣 Add SSI Fellowship 2022 Lauch Webinar to speaking page

content/blog/test-this-pr.md
Add test-this-pr blog to website
=> ✨ Add test-this-pr blog

config.toml
Some minor tweaks to the website metadata
=> Update tag line for website

.mergify.yml
Add shellcheck as required condition
=> Update mergify rules

config.toml, layouts/partials/navbar.html
This will allow main menu items to become dropdown menus
=> Adding submenu functionality to nav bar

config.toml, content/blog/collabw21.md, content/blog/continuous-integration.md, content/blog/diving-into-leadership.md, content/blog/hugo-tutorial.md, content/blog/ssi-fellowship.md, content/blog/test-this-pr.md, content/media.md, content/project/binder.md, content/project/helmupgradebot.md, content/project/turing-way.md, content/speaking.md
Support a tag taxonomy and blog posts that form a series
=> Taxonomies and Series

.github/workflows/autoupdate-theme.yaml
Automatically run `git submodule update --remote` in CI and open a Pull Request
=> Create CI workflow to automatically update the website theme

.github/workflows/auto-tweet-blogs.yaml
Doesn't tweet yet - needs testing!
=> Add GitHub workflow to automatically tweet out new blog posts

.github/workflows/auto-tweet-blogs.yaml
Include the content/blog prefix
=> Update pattern matching expression on filenames

content/blog/test-this-pr.md
This adds some harmless whitespace to a blog post to test the updated auto-tweet workflow
=> [TEST] Modify a blog post by adding whitespace

content/blog/test-this-pr.md
Reverts sgibson91/sgibson91.github.io#132
=> Revert "[TEST] Modify a blog post by adding whitespace"

content/blog/test-this-pr.md
Reverts sgibson91/sgibson91.github.io#133
=> Revert "Revert "[TEST] Modify a blog post by adding whitespace""

content/blog/test-this-pr.md
Reverts sgibson91/sgibson91.github.io#134
=> Revert "Revert "Revert "[TEST] Modify a blog post by adding whitespace"""

.github/workflows/build-and-deploy.yaml, config.toml, content/_index.md, content/blog/2i2c-ci-cd-improvements.md, content/blog/collabw21.md, content/blog/continuous-integration.md, content/blog/diving-into-leadership.md, content/blog/hugo-tutorial.md, content/blog/ssi-fellowship.md, content/blog/test-this-pr.md
=> Swap out action to check html

.github/workflows/build-and-deploy.yaml, .github/workflows/linkcheck.yaml
=> Remodel linkcheck CI

.github/workflows/linkcheck.yaml, .mergify.yml
- Trigger linkcheck on push and pull_request events
- Allow failing of linkcheck step in pull request context
- Update mergify rules to respect linkcheck in pull requests
=> CI updates

.github/workflows/build-and-deploy.yaml, .github/workflows/linkcheck.yaml
=> Pin hugo version

.github/workflows/linkcheck.yaml
Too much noise. Solution would be to create or update.
=> Pause creating issues for broken links for now

content/blog/ssi-fellowship.md
Was causing the build to break
=> Remove tweet

config.yaml
looks slightly tidier, requires adding `fa-fw` as a class to activate the fontawesome fixed width config
fix #
-
=> add fixed width icon to skills/experience etc on homepage

config.yaml
=> Add extra bullets pointing out Python or infra skills
